# Generated by Django 4.1.2 on 2022-11-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rating_otzyv_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, upload_to='movies/posters', verbose_name='Постер'),
        ),
    ]
